{
 "title": "SSL/TLS Exporter",
 "description": "Shows certitificate expiration times, as well as failed ssl connects",
 "tags": [
  "ssl",
  "tls"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(ssl_probe_success, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=~\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "SSL Certificates Endpoints",
   "type": "table-old",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "((ssl_cert_not_after{instance=~\"$instance\",job=~\"$job\"} - time())/24/60/60)"
    }
   ]
  },
  {
   "title": "Сеrtificates expires",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "d", "label": "Expires in" }
   ],
   "targets": [
    {
     "expr": "(ssl_cert_not_after - time())/24/60/60",
     "legendFormat": "{{cn}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Failed SSL Connects History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(up{job=~\"$job\", instance=~\"$instance\"} == 0 or ssl_probe_success{job=~\"$job\", instance=~\"$instance\"} == 0)^0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Unique Certificates",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max(ssl_cert_not_after{instance=~\"$instance\",job=~\"$job\"}) by (issuer_cn,serial_no))"
    }
   ]
  },
  {
   "title": "Failed SSL Connects - $job",
   "type": "table-old",
   "description": "Possible reasons:\n- site is down\n- server is down\n- certificate has expired\n- certificate's CA is not trusted by the exporter\n- other connection errors\n- other certificate errors",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 38 },
   "repeat": "job",
   "targets": [
    {
     "expr": "ssl_probe_success{instance=~\"$instance\",job=~\"$job\"} == 0"
    }
   ]
  },
  {
   "title": "SSL Certificates files",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "((ssl_file_cert_not_after{instance=~\"$instance\",job=~\"$job\"} - time())/24/60/60)"
    }
   ]
  }
 ]
}